In [10]:
#1. What is a Python library? Why do we use Python libraries

"""
A Python library is a collection of modules or packages containing pre-written code tht can be 
utilized to perform specific tasks or functions.
These libraries are designed to simplify the development processes 
by providing reusable functions and classes that can be easily 
impoted into your python programs.

#uses -
1.code Reusability -
Libraries contain pre-built functions and modules ,allowing developers to reuse 
code that has already been written and tested.

2.Time efficiency - 
By leveraging existing libraries,developers can save time and effort in coding 
complex algorithms or functionalities from scratch .

"""

#2. What is the difference between Numpy array and List?

""" 
1.Homogeneity -
Numpy array - numpy arrays are homogeneous ,meaning all elements must be of the 
same data type.
lists - Python list can contain elements of different types .

2.Memory efficient -
Numpy array- They are more memory effiecient compared to lists,
especially for large datasets ,because they are implemented in C and have a fixed 
data type .
lists - Pyton lists are  more flexible but may have higher overhead because each 
element can be of a different type.

3.Performance -
numpy array - numpy operations are often faster than equivalent operations on list
due to the homogeneity and optimized operations .

lists - Lists are generally slower for numericals because they are more flexible 
and need to handle elements of varying data types.
 """
# 3. Find the shape, size and dimension of the following array.
import numpy as np 
       
arr = np.array(  [[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

#size
print("size :")
a = arr.size
print(a)
#shape
print('shape')
b = arr.shape
print(b)

#dimension
print('dimension')
c = arr.ndim
print(c)

#4. Write python code to access the first row of the following array

r = arr[0]
print("row :",r)

# 5. How do you access the element at the third row and fourth column from the given numpy array

d = arr[[2],[3]]
print(d)
#6. Write code to extract all odd-indexed elements from the given numpy array
odd_indexed = arr[1::2, : ]
print(odd_indexed)

#7.How can you generate a random 3x3 matrix with values between 0 and 1?

arr1 = np.random.rand(3,3)
print(arr1)

#8. Describe the difference between np.random.rand and np.random.randn

#np.random.rand - 
##It generates random number from a uniform distribution in the half open interval[0,1).
arr1 = np.random.rand(3,3)
print("using rand :",arr1,)

#np.random.randn- 
##Generates random number where distribution is not uniform ,generated value can be positive and negative 

arr1 = np.random.randn(3,3)
print("\nusing randn:",arr1)

#9. Write code to increase the dimension of the following array?
print("original array:")
print(arr)
arr3 = np.expand_dims(arr,axis = 0 )
print("\nIncreased dimension:")
print(arr3)

# 10. How to transpose the following array in NumPy?
print("Transposed array:")
print(arr.T)

#Consider the following matrix:
matrixa =  [[1, 2, 3, 4] ,
            [5, 6, 7, 8],
             [9, 10, 11, 12]]


matrixb =  [[1, 2, 3, 4], 
            [5, 6, 7, 8],
             [9, 10, 11, 12]]

#1.indexwise multiplication 
print('indexed wise multiplication:')
arr_m1 = np.array(matrixa)
arr_m2 = np.array(matrixb)

index_mul  = arr_m1 * arr_m2 
print(index_mul)

#2.Matrix Multiplication - 
print("Matrix multiplication : In this scenarion not possible ")
#matrix_mul = np.dot(arr_m1,arr_m2)  not possible 

#3.Add matrices 
print("Matrix Addition :")
add_mt = arr_m1 + arr_m2 
print(add_mt)

#4.Subtract 

print("Subtraction :")
sub_mt = arr_m1 - arr_m2 
print(sub_mt)
#5.division matrices 
print("Division :")
div_mt = arr_m2/arr_m1
print(div_mt)

#12.  Which function in Numpy can be used to swap the byte order of an array?

arr = np.array([1,2,3,4],dtype = np.int32)
arr.byteswap(True)
print(arr)
# 13.  What is the significance of the np.linalg.inv function?

"""It is used to compute multiplicative inverse of a matrix 
"""

a = np.array([[1,2],
             [3,4]])

a_inv = np.linalg.inv(a)
print(a_inv)
# 14. What does the np.reshape function do, and how is it used?
"""It is used to change the shape of an array without changing the data """
print("REShape : ")
arr2 = np.array([2,3,4,5,6,7])
reshape_arr = np.reshape(arr2,(3,2))
print(reshape_arr)

# 15. What is broadcasting in Numpy?

""" Broadcasting is a powerful features in Numpy that allows opetations on array 
of different shapes and sizes without the need for explicit or duplication .

-It enables  Numpy to perform  element wise operation in arrays of different shape by 
automatically aligning the dimensions .

"""

size :
12
shape
(3, 4)
dimension
2
row : [1 2 3 4]
[12]
[[5 6 7 8]]
[[0.30457259 0.95637338 0.86258771]
 [0.07912014 0.68005077 0.87737979]
 [0.75645428 0.48095959 0.29541602]]
using rand : [[0.52101847 0.40146524 0.26232858]
 [0.84970132 0.30908095 0.91960539]
 [0.54542937 0.40317093 0.32328521]]

using randn: [[ 0.15747782 -0.0021169   0.09221249]
 [ 0.66142193 -0.58711876  0.91831316]
 [-0.34891225  0.3947443  -0.23490363]]
original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
indexed wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication : In this scenarion not possible 
Matrix Addition :
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction :
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[16777216 33554432 50331648 67108864]
[[-2.   1. ]
 [ 1.

' Broadcasting is a powerful features in Numpy that allows opetations on array \nof different shapes and sizes without the need for explicit or duplication .\n\n-It enables  Numpy to perform  element wise operation in arrays of different shape by \nautomatically aligning the dimensions .\n\n'